import  AppComp from'./AppComp';
import Heading from './Heading';
import TitlePass2  from './TitlePass2';
import TitlePass1jsx  from './TitlePass1jsx';
import TitlePass2jsx  from './TitlePass2jsx';
import Buttonchange  from './Buttonchange';
import Inputchange from './Inputchange';
import Formcomp from './Formcomp';
// import TitlePass from '../pages/titlepass/TitlePass';
export{AppComp, Buttonchange, Inputchange, Heading,Formcomp,TitlePass2,TitlePass1jsx,TitlePass2jsx};